[config]
version_check = false

[templates.colors]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/matugen/colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/matugen.css'
post_hook = 'pkill -SIGUSR2 waybar || true'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/matugen.css'
post_hook = 'swaync-client -rs || true'

[templates.swayosd]
input_path = '~/.config/matugen/templates/swayosd.css'
output_path = '~/.config/swayosd/matugen.css'
post_hook = 'pkill -SIGUSR2 swayosd-server || true'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.local/share/rofi/themes/matugen.rasi'
