# Font
font_family      IosevkaTerm Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16.0

# Cursor
cursor_blink_interval 0
shell_integration no-cursor

# Mouse
mouse_hide_wait 1.0

# Scrollback
scrollbar never

# Background
background_opacity 0.8
dynamic_background_opacity yes

# BEGIN_KITTY_THEME
# Everforest Dark Hard
include current-theme.conf
# END_KITTY_THEME
